### ISSUE TITLE
json.loads(params["json_string"]) 

### ISSUE THREAD

**Issue by MatteoZhang** [paolo-26/Programming-for-IoT-Applications#1]
params["json_string"] dove lo hai preso?
direttamente vedendo dal post? 
('saveDashboard',) {'json_string': ...

class WebService(object):
    exposed = True

    def GET(self, *uri, **param):
        with open("freeboard/index.html") as fp:
            index = fp.read()
        print uri, param
        return index

    def POST(self, *uri, **params):
        dash = json.loads(params["json_string"])  # Load json object
        with open("./freeboard/dashboard/dashboard.json", "w") as f:
            json.dump(dash, f, indent=2)  # Write json to file
        print uri, params
if __name__=='__main__':
    cherrypy.tree.mount(WebService(), '/', config='server.conf')
    cherrypy.config.update('server.conf')
    cherrypy.engine.start()
    cherrypy.engine.block()

**Comment by paolo-26** [comment]
Ho stampato il contenuto della risposta alla POST e ho visto che il json stava dentro "json_string"
